# Generated by Django 4.2.7 on 2026-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_source',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('facebook', 'Facebook')], default='local', max_length=20),
        ),
    ]
