services:
  db:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: blog_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: blog_api
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: django-insecure-docker-secret-key
      DEBUG: "True"
      DB_NAME: blog_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0

volumes:
  postgres_data:
